Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b69ea66ff7391e80
      Tags:
        - Key: Name
          Value: Bootcamp Demo
