Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0b69ea66ff7391e80
      Tags:
        - Key: "Name"
          Value: !Join
            - " "
            - - "EC2 Instance for"
              - !Ref AWS::Region
              - !Ref AWS::StackName
      SecurityGroups:
        - !Ref MySecurityGroup
  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SSH on port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
